# Config.yaml - Config file for PicBit Backend
# Parameters: 
# 	- Domain: Defines the endpoint in which PicBit is deployed (this param is used in the session cookie generation)
# 	- Component_versioning: Sets if the components will be served in a static (always serve stable version of the component) 
#						   or dynamic (serve random version of the component) basis. Posible values: static | dynamic

domain: centauro.ls.fi.upm.es
domainTest: test.centauro.ls.fi.upm.es
#domain: localhost
component_versioning: dynamic
APP_ID: 123747765045661
APP_SECRET: 62f8896c4428d87f0c60c014d2cc2df1
FACEBOOK_CONFIG:
  url: https://graph.facebook.com/v2.10/me/feed
  fields: "name,updated_time,attachments,story_tags,place,from,icon,message,object_id,likes,source,story,type, message_tags"
  url_id: https://graph.facebook.com/v2.10/me?fields=id
  url_friends: https://graph.facebook.com/v2.10/me/friends
  locale: es_es