# Config.yaml - Config file for PicBit Backend
# Parameters: 
# 	- Domain: Defines the endpoint in which PicBit is deployed (this param is used in the session cookie generation)
# 	- Component_versioning: Sets if the components will be served in a static (always serve stable version of the component) 
#						   or dynamic (serve random version of the component) basis. Posible values: static | dynamic

domain: centauro.ls.fi.upm.es
domainTest: test.centauro.ls.fi.upm.es
#domain: localhost
component_versioning: dynamic
