domain: centauro.ls.fi.upm.es
domainTest: test.centauro.ls.fi.upm.es
component_versioning: dynamic
APP_ID: <app_id_facebook>
APP_SECRET: <app_secret_facebook>
FACEBOOK_CONFIG:
  url: https://graph.facebook.com/v2.10/me/feed
  fields: "name,updated_time,attachments,story_tags,place,from,icon,message,object_id,likes,source,story,type, message_tags"
  url_id: https://graph.facebook.com/v2.10/me?fields=id
  url_friends: https://graph.facebook.com/v2.10/me/friends
  locale: es_es
scopes: 
  googleplus:
    default: "https://www.googleapis.com/auth/contacts https://www.googleapis.com/auth/contacts.readonly"
    security: >
      https://www.googleapis.com/auth/contacts
      https://www.googleapis.com/auth/plus.me
  facebook:
    default: "user_posts,user_friends"
    security: "public_profile,read_stream, user_friends, email, user_about_me, user_actions, user_actions, user_actions, user_actions, user_actions, user_actions, user_birthday, publish_pages, publish_actions, rsvp_event, pages_manage_cta"
  pinterest:
    default: "read_public,read_relationships"
    security: "read_public,write_public,read_relationships,write_relationships"
  spotify:
    default: "user-read-private user-follow-read user-read-email"
    security: "user-read-private user-read-email user-follow-modify user-follow-read user-top-read user-read-playback-state"
  reddit:
    default: "read mysubreddits"
    security: "edit flair history modflair modlog modposts mysubreddits  read report save submit subscribe  wikiedit"
versions:
  - stable
  - latency
  - security
  - structural
  - usability
  - maintenance
  - accuracy
  - complexity
components:
  - twitter-timeline
  - facebook-wall
  - pinterest-timeline
  - googleplus-timeline
  - traffic-incidents
  - finance-search
  - open-weather
  - spotify-component"
  - reddit-timeline
