application: example-project-13
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Route handlers
- url: /.*
  script: manejador_pb.app

libraries:
- name: webapp2
  version: latest