application: example-project-13
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Route handlers
- url: /favicon\.ico
  static_files: ../favicon.ico
  upload: favicon\.ico

- url: /
  static_files: static/index.html
  upload: index\.html

- url: /api/oauth
  script: manejador_pb.app
  secure: always

- url: /api/.*
  script: manejador_pb.app
  
- url: /formulario
  static_files: static/index.html
  upload: index\.html

- url: /user/.*
  static_files: static/index.html
  upload: index\.html
  
- url: /
  static_dir: static 


libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest